### ISSUE TITLE
Failed test 'Catalyst/Plugin/OIDC.pm loaded ok'

### ISSUE THREAD

**Issue by eserte** [sebmourlhou/oidc-client#2]
The test suite fails on some of my smoker systems like this:
```
#   Failed test 'Catalyst/Plugin/OIDC.pm loaded ok'
#   at t/00-compile.t line 56.
#          got: '65280'
#     expected: '0'
You can only consume roles, Catalyst::ClassData is not a Moose role at /home/cpansand/.cpan/build/2025011020/Moose-2.2207-0/blib/lib/Moose/Exporter.pm line 418
	Moose::with('Catalyst::ClassData') called at /home/cpansand/.cpan/build/2025011020/OIDC-Client-0.01-0/blib/lib/Catalyst/Plugin/OIDC.pm line 5
	require Catalyst/Plugin/OIDC.pm at -e line 1
Compilation failed in require at -e line 1.
# Looks like you failed 1 test of 14.
t/00-compile.t ............................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/14 subtests 
```

**Comment by sebmourlhou** [comment]
I've fixed the dependencies.
It should work with the new version (0.02).
